---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
    exclude_fingerprints:
    # complexity in PayloadValidator#validate
    - 1b18d0fde7d0511be196bcc366180bf8
    # complexity in Runner#run
    - c1a982077efa39ca50db944490e15485
ratings:
  paths:
  - "**.inc"
  - "**.module"
  - "**.py"
exclude_paths:
- dist/
- tests/
- build/
