name: lint-test

on: [push]

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and test
      run: mvn clean install
    - name: Coverage
      run: mvn sonar:sonar \
        -Dsonar.projectKey=Luke31_gluemotion \
        -Dsonar.organization=luke31 \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}
